modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "WTFPL"

[[mods]]
modId = "yourmodideas"
version = "${version}"
displayName = "Your Mod Ideas"
authors = "SSBlur"
description = '''
I put your ideas in the game!
'''
#logoFile = ""

[[dependencies.yourmodideas]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.yourmodideas]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.yourmodideas]]
modId = "architectury"
mandatory = true
versionRange = "[9.1.12,)"
ordering = "AFTER"
side = "BOTH"