modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "CC0-1.0"

[[mods]]
modId = "obt"
version = "${version}"
displayName = "One Billion Things"
authors = "SSBlur"
description = '''
Ideas come alive!
'''
logoFile = "icon.png"

[[dependencies.scriptor]]
modId = "neoforge"
type = "required"
versionRange = "[20.6,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.scriptor]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.6,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.scriptor]]
modId = "architectury"
type = "required"
versionRange = "[12.0.28,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "obt.mixins.json"
