name: build

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    environment: publish
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: changelog
        uses: ssblur/git-changelog-action@v1
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: Build Forge
        run: bash ./gradlew forge:signedJar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USER: 'ssblur'
          JAR_SIGNING_STORE: ${{ secrets.JAR_SIGNING_STORE }}
          JAR_SIGNING_ALIAS: ${{ secrets.JAR_SIGNING_ALIAS }}
          JAR_SIGNING_STORE_PASS: ${{ secrets.JAR_SIGNING_STORE_PASS }}
          JAR_SIGNING_KEY_PASS: ${{ secrets.JAR_SIGNING_KEY_PASS }}
      - name: Build Fabric
        run: bash ./gradlew fabric:signedJar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USER: 'ssblur'
          JAR_SIGNING_STORE: ${{ secrets.JAR_SIGNING_STORE }}
          JAR_SIGNING_ALIAS: ${{ secrets.JAR_SIGNING_ALIAS }}
          JAR_SIGNING_STORE_PASS: ${{ secrets.JAR_SIGNING_STORE_PASS }}
          JAR_SIGNING_KEY_PASS: ${{ secrets.JAR_SIGNING_KEY_PASS }}
      - name: Cleanup
        run: |
          rm */build/libs/yourmodideas-*-dev-shadow.jar
          bash -c 'for file in fabric/build/libs/*.jar; do mv "$file" "${file%.jar}-fabric.jar"; done'
          bash -c 'for file in forge/build/libs/*.jar; do mv "$file" "${file%.jar}-forge.jar"; done'
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Release
          path: |
            fabric/build/libs/yourmodideas-*-sgd-*.jar
            forge/build/libs/yourmodideas-*-sgd-*.jar
            modkey.cer
      - name: "Release"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            fabric/build/libs/yourmodideas-*-sgd-*.jar
            forge/build/libs/yourmodideas-*-sgd-*.jar
            modkey.cer
      - name: Extract Tag Version
        id: tag
        run: echo "version=${GITHUB_REF:11}" >> $GITHUB_OUTPUT
      - name: "Upload Fabric to CurseForge"
        uses: itsmeow/curseforge-upload@v3
        with:
          file_path: fabric/build/libs/yourmodideas-${{ steps.tag.outputs.version }}-sgd-fabric.jar
          game_endpoint: "minecraft"
          relations: "fabric-api:requiredDependency,architectury-api:requiredDependency"
          game_versions: "Minecraft 1.20:1.20.2,Java 17,Java 18,Fabric,Client,Server"
          project_id: "949016"
          token: "${{ secrets.CURSEFORGE_TOKEN }}"
          changelog_type: text
          changelog: |
            Autogenerated: 
            ${{ steps.changelog.outputs.changelog }}
      - name: "Upload Forge to CurseForge"
        uses: itsmeow/curseforge-upload@v3
        with:
          file_path: forge/build/libs/yourmodideas-${{ steps.tag.outputs.version }}-sgd-forge.jar
          game_endpoint: "minecraft"
          relations: "architectury-api:requiredDependency"
          game_versions: "Minecraft 1.20:1.20.2,Java 17,Java 18,Forge,Client,Server"
          project_id: "949016"
          token: "${{ secrets.CURSEFORGE_TOKEN }}"
          changelog_type: text
          changelog: |
            Autogenerated: 
            ${{ steps.changelog.outputs.changelog }}